#!/usr/bin/env node
var host = "golf.dev:8080";
var build_dir = "development_build";
if( process.env.NODE_ENV === "production") {
  host = "golf.riesd.com";
  build_dir = "production_build";
}

fs = require('fs')
fs.readFile('app/index.html', 'utf8', function (err,data) {
  if (err) {
    console.log(err);
    process.exit(1);
  }
  fs.writeFile(build_dir + '/index.html', data.replace(/\:host\:/g,host), function(err){
    if (err) {
      console.log(err);
      process.exit(1);
    }
  });
});
