#!/usr/bin/env node
var host = "localhost:8080";
if( process.env.NODE_ENV === "production") {
  host = "golf.riesd.com";
}

fs = require('fs')
fs.readFile('app/index.html', 'utf8', function (err,data) {
  if (err) {
    console.log(err);
    process.exit(1);
  }
  fs.writeFile('build/index.html', data.replace(":host:",host), function(err){
    if (err) {
      console.log(err);
      process.exit(1);
    }
  });
});
